package com.contractrisk.entity.enums;

public enum ClauseSection {
    PARTIES_INFO,
    DEFINITIONS,
    RIGHTS_AND_OBLIGATIONS,
    BREACH_LIABILITY,
    DISPUTE_RESOLUTION,
    CONFIDENTIALITY,
    INTELLECTUAL_PROPERTY,
    PAYMENT_TERMS,
    TERM_AND_TERMINATION,
    FORCE_MAJEURE,
    MISCELLANEOUS,
    SUPPLEMENTARY,
    OTHER
}
