package com.contractrisk.entity.enums;

public enum OperationType {
    UPLOAD_VERSION,
    VIEW_VERSION,
    ROLLBACK_VERSION,
    EXPORT_REPORT,
    VIEW_CHANGE_DIFF,
    IMPACT_ASSESSMENT,
    BATCH_DELETE_VERSION,
    UPDATE_VERSION_NOTE,
    ADD_VERSION_TAG,
    REMOVE_VERSION_TAG,
    EXPORT_COMPARISON_PDF
}
